version: "3.9"

services:
  auth:
    container_name: "auth"
    build: .
    command: build/auth
    restart: always
    ports:
      - "8080:8080"
      - "8099:8099"
    expose:
      - "8080"
      - "8099"
    networks:
      - postgres
    depends_on:
      user_db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  user_db:
    image: postgres
    container_name: "user_db"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SSL_MODE: disable
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./build/local/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      postgres:
        aliases:
          - user_db

  migration:
    container_name: "migration"
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command:
      - "-path=/migrations"
      - "-database=postgres://${DB_USERNAME}:${DB_PASSWORD}@user_db:5432/${DB_NAME}?sslmode=disable"
      - "up"
    depends_on:
      user_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
